### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by limeschool** [MadeByEmil/oku#12]
# Development goals
- [ ] Capture page load event, download IPFS page, redirect from "ipfs" scheme to local cache (implementing IPFS links)
- [ ] Capture refresh event, update URL in navbar
- [ ] Search through page, download referenced IPFS files
---
- [ ] Tabs (by first public release)
- [ ] New windows (by first public release)
- [ ] Branding (by first public release)
- [ ] Better spacing of UI (by first public release)
---
- [ ] Show directory when giving IPFS directory instead of file (long-term)
- [ ] Render Markdown files (long-term)
- [ ] Render simple Mokk Files (long-term)
- [ ] Browser settings page (long-term)
- [ ] IPFS GUI (manage files, push to IPNS, etc) (long-term)
